export const localMedia = {
    portraits: [
        '/media/portrait-lily.jpg',
        '/media/avatar-deer.jpg',
        '/media/avatar-ken.jpg',
        '/media/avatar-sophie.jpg',
        '/media/avatar-elaine.jpg',
        '/media/avatar-student.jpg',
        '/media/avatar-david.jpg',
        '/media/avatar-senior.jpg',
    ],
    aiPortraits: [
        '/lily/cuts/lily-heart-hoodie.png',
        '/lily/cuts/lily-wave-sport.png',
        '/lily/cuts/lily-water-sport.png',
        '/lily/cuts/lily-salad-sport.png',
        '/lily/cuts/lily-phone-sport.png',
        '/lily/cuts/lily-ok-sport.png',
        '/lily/cuts/lily-dumbbell-sport.png',
        '/lily/cuts/lily-stretch-sport.png',
    ],
    avatars: {
        lily: '/media/portrait-lily.jpg',
        deer: '/media/avatar-deer.jpg',
        ken: '/media/avatar-ken.jpg',
        sophie: '/media/avatar-sophie.jpg',
        elaine: '/media/avatar-elaine.jpg',
        student: '/media/avatar-student.jpg',
        david: '/media/avatar-david.jpg',
        senior: '/media/avatar-senior.jpg',
    },
    lilyPoses: {
        heart: '/lily/cuts/lily-heart-hoodie.png',
        wave: '/lily/cuts/lily-wave-sport.png',
        ok: '/lily/cuts/lily-ok-sport.png',
        water: '/lily/cuts/lily-water-sport.png',
        salad: '/lily/cuts/lily-salad-sport.png',
        phone: '/lily/cuts/lily-phone-sport.png',
        mat: '/lily/cuts/lily-mat-sport.png',
        dumbbell: '/lily/cuts/lily-dumbbell-sport.png',
        stretch: '/lily/cuts/lily-stretch-sport.png',
    },
    lucyPoses: {
        athleteBlack: '/ann/cuts/lucy-other/lucy-athlete-black.png',
        knitCream: '/ann/cuts/lucy-other/lucy-knit-cream.png',
        waveGreen: '/ann/cuts/lucy-other/lucy-wave-green.png',
        coffeeBlue: '/ann/cuts/lucy-other/lucy-coffee-blue.png',
        tabletPurple: '/ann/cuts/lucy-other/lucy-tablet-purple.png',
        blazerBeige: '/ann/cuts/lucy-other/lucy-blazer-beige.png',
        thinkBlue: '/ann/cuts/lucy-other/lucy-think-blue.png',
        cheerBlack: '/ann/cuts/lucy-other/lucy-cheer-black.png',
    },
    scenes: {
        mealBowl: '/media/scene-meal-bowl.jpg',
        mealCard: '/media/scene-meal-card.jpg',
        analysis: '/media/scene-analysis.jpg',
        sleep: '/media/scene-sleep.jpg',
        team: '/media/scene-team.jpg',
        progress: '/media/scene-progress.jpg',
        community: '/media/scene-community.jpg',
        rice: '/media/scene-rice.jpg',
        fish: '/media/scene-fish.jpg',
        greens: '/media/scene-greens.jpg',
    },
    articles: {
        breakfast: '/media/article-breakfast.jpg',
        workout: '/media/article-workout.jpg',
        plateau: '/media/article-plateau.jpg',
        dinner: '/media/article-dinner.jpg',
        steps: '/media/article-steps.jpg',
        habits: '/media/article-habits.jpg',
    },
};